### ISSUE TITLE
Allow users to add customized rules

### ISSUE THREAD

**Issue by milton0825** [nilslice/protolock#54]
Users may want to register their own customized rules (for example, enforce no field removal entirely for some protobuf messages) and ideally those customized rules should live out side the space of protolock repository.

Currently protolock supports checks based on the rules defined in https://github.com/nilslice/protolock/blob/master/rules.go#L11

We may need a way to register customized checks.

**Comment by nilslice** [comment]
@milton0825 - this is interesting, especially after taking a closer look at your closed PR. I see what you mean where the ability to do more custom "comparison" of a `Protolock` from the `proto.lock` (current) and the parsed set (updated) of proto files would benefit teams with more specific needs. 

At first glance, it seems like this would be very difficult to support in a dynamic way (e.g. using a configuration file to enable/disable rules, or define custom ones). However, if you were to take a look at the implementation code of the CLI, it uses the `nilslice/protolock` code as a library, which some parts are exposed to callers as exported funcs. 

Do you think you could attempt building your own CLI that would run after `protolock` but instead of directly using [`Status`](https://github.com/nilslice/protolock/blob/master/status.go#L10), you would use the funcs within `nilslice/protolock` as an imported package within your own separate CLI? 

I assume you would need to PR some changes to this repo, where the current funcs are unexported -- I'm completely fine with exporting any of them if you need.

To demonstrate this, you could call these functions (which would need to be exported): https://github.com/nilslice/protolock/blob/master/parse.go#L305-L329 to get the "current" `Protolock` (as defined in `proto.lock` file)

And compare it using your own rules using the `Protolock` you get from this func (also needs exporting): https://github.com/nilslice/protolock/blob/master/parse.go#L402-L452

The end result is that you would have a separate binary CLI to run after the main `protolock` binary CLI in your build process, but it would allow you to make it as custom as you'd like while still using the same `proto.lock` file.

Let me know if this makes sense or if there are other constraints I'm not considering.

If you end up considering this path, and are able to open source the code, I would love to link to your project from here to help others make custom rules of their own or use yours 👍

**Comment by milton0825** [comment]
@nilslice thanks for the feedback. I think we can refactor the code a bit and expose a function that takes customized rules from user and check if changes pass those rules.

**Comment by nilslice** [comment]
Closing as #58 solves.
